<center>
<div class="default">
<table class="menu" align="center" border=0 cellpadding=0 cellspacing=0 width=100%>
<tr>
	<td><a href="entradab.php">Inicio</a></td>
	<td><a href="alta_usuario.php">Nuevo Abogado</a></td>
	<td><a href="update_usuario.php">Modificar Abogado</a></td>
	<td><a href="alta_tribunal.php">Nuevo Tribunal</a></td>
	<td><a href="update_tribunal.php">Modificar Tribunal</a></td>
	<td><a href="alta_demanda.php">Nuevo Juicio</a></td>
</tr>
<tr>
	<td><a href="modifica_demanda.php">Modificar Juicio</a></td>
	<td><a href="alta_testigo.php">Agregar Hecho</a></td>
	<td><a href="alta_suceso.php">Nuevo Suceso</a></td>
	<td><a href="update_suceso.php">Modificar Suceso</a></td>
	<td><a href="Desp-Demanda.php">Reportes</a></td>
</tr>
<tr>
	<td colspan=6><hr></td>
</tr>
<tr>
	<td colspan=6><a href="index.html">Salir</a></td>
</tr>
</table>
</div>
</center>